version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-non-dev
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: identification_app
    ports:
      - "2785:8000"
    depends_on:
      - db